{% set name = "apache-beam" %}
{% set version = "2.41.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: c1a0456a5b48c3481bf20dc904e4d812515144336873b322f17ba188e2fabd92
  patches:
    - 0001-pyarrow-relaxed.patch

build:
  number: 1

requirements:
  host:
    - python {{ python }}
  run:
    - python {{ python }}

outputs:
  - name: {{ name }}
    script: build_apache_beam.sh
    requirements:
      build:
        - python {{ python }} 
        - cython {{ cython }}                        
        - {{ compiler('c') }}
      host:
        - python {{ python }}
        - cython {{ cython }}
        - pip
      run:
        - python {{ python }}
        - cython >=0.28.1
        - crcmod >=1.7,<2.0
        - dill >=0.3.1.1,<0.3.2
        - cloudpickle >=2.1.0,<3
        - fastavro >=0.23.6,<2
        - grpcio {{ grpcio }}
        - python-hdfs >=2.1.0,<3.0.0
        - httplib2 >=0.8,<0.20.0
        - numpy {{ numpy }}
        - orjson <4.0
        - protobuf {{ protobuf }}
        - proto-plus >=1.7.1,<2
        - pyarrow {{ arrow }}
        - pydot >=1.2.0,<2
        - python-dateutil >=2.8.0,<3
        - pymongo >=3.8.0,<4.0.0
        - pytz >=2018.3
        - requests {{ requests }}
        - typing-extensions {{ typing_extensions }}

    test:
      requires:
        - pip
      imports:
        - apache_beam
        - apache_beam.coders
        - apache_beam.examples.complete.game
        - apache_beam.examples.complete.juliaset
        - apache_beam.examples.complete.juliaset.juliaset
        - apache_beam.examples.cookbook
        - apache_beam.examples.flink
        - apache_beam.examples.snippets
        - apache_beam.internal
        - apache_beam.internal.gcp
        - apache_beam.io
        - apache_beam.io.flink
        - apache_beam.io.gcp
        - apache_beam.io.gcp.datastore
        - apache_beam.io.gcp.internal
        - apache_beam.io.gcp.tests
        - apache_beam.metrics
        - apache_beam.options
        - apache_beam.portability
        - apache_beam.portability.api
        - apache_beam.runners
        - apache_beam.runners.dataflow
        - apache_beam.runners.direct
        - apache_beam.runners.interactive
        - apache_beam.runners.interactive.display
        - apache_beam.runners.job
        - apache_beam.runners.portability
        - apache_beam.runners.test
        - apache_beam.runners.worker
        - apache_beam.testing
        - apache_beam.testing.benchmarks
        - apache_beam.testing.benchmarks.nexmark
        - apache_beam.testing.benchmarks.nexmark.models
        - apache_beam.testing.benchmarks.nexmark.queries
        - apache_beam.tools
        - apache_beam.transforms
        - apache_beam.typehints
        - apache_beam.utils
      commands:
        - pip check

    test:
      imports:
        # not sure what test is useful...
        - apache_beam
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://beam.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Apache Beam: An advanced unified programming model'

  description: |
    Apache Beam is an open source, unified model for defining both batch
    and streaming data-parallel processing pipelines. Using one of the open
    source Beam SDKs, you build a program that defines the pipeline. The
    pipeline is then executed by one of Beam’s supported distributed
    processing back-ends, which include Apache Apex, Apache Flink, Apache
    Spark, and Google Cloud Dataflow.
  doc_url: https://beam.apache.org/documentation/
  dev_url: https://github.com/apache/beam

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
